export { default as IconMessage} from '@assets/icons/message.svg?react';
export { default as IconRight} from '@assets/icons/right.svg?react';
export { default as IconEye} from '@assets/icons/eye.svg?react';
export { default as IconEyeClose} from '@assets/icons/eye-close.svg?react';
export { default as IconPercentage} from '@assets/icons/percentage.svg?react';
export { default as IconCalender} from '@assets/icons/calender.svg?react';
export { default as IconPaymentMethodVisa} from '@assets/icons/payment-method-visa.svg?react';
export { default as IconChevronLeft} from '@assets/icons/chevron-left.svg?react';
export { default as IconChevronRight} from '@assets/icons/chevron-right.svg?react';
