export { default as IconCalender } from '@assets/icons/calender.svg?react';
export { default as IconChecked } from '@assets/icons/checked.svg?react';
export { default as IconChevronDown } from '@assets/icons/chevron-down.svg?react';
export { default as IconChevronLeft } from '@assets/icons/chevron-left.svg?react';
export { default as IconChevronRight } from '@assets/icons/chevron-right.svg?react';
export { default as IconClear } from '@assets/icons/clear.svg?react';
export { default as IconClose } from '@assets/icons/close.svg?react';
export { default as IconEyeClose } from '@assets/icons/eye-close.svg?react';
export { default as IconEye } from '@assets/icons/eye.svg?react';
export { default as IconMessage } from '@assets/icons/message.svg?react';
export { default as IconMinus } from '@assets/icons/minus.svg?react';
export { default as IconPaymentMethodVisa } from '@assets/icons/payment-method-visa.svg?react';
export { default as IconPercentage } from '@assets/icons/percentage.svg?react';
export { default as IconPlus } from '@assets/icons/plus.svg?react';
export { default as IconRight } from '@assets/icons/right.svg?react';
export { default as IconExclude } from '@assets/icons/exclude.svg?react';
export { default as IconCopy } from '@assets/icons/copy.svg?react';
export { default as IconCheck } from '@assets/icons/check.svg?react';
export { default as IconClipboard } from '@assets/icons/clipboard.svg?react';
export { default as IconHamburger } from '@assets/icons/hamburger.svg?react';
export { default as IconSearch } from '@assets/icons/search.svg?react';
export { default as IconArrowUp } from '@assets/icons/arrow-up.svg?react';
export { default as IconArrowDown } from '@assets/icons/arrow-down.svg?react';
export { default as IconSort } from '@assets/icons/sort.svg?react';
export { default as IconInfo } from '@assets/icons/info.svg?react';
export { default as IconSuccess } from '@assets/icons/success.svg?react';
export { default as IconDanger } from '@assets/icons/danger.svg?react';
export { default as IconNotification } from '@assets/icons/notification.svg?react';
export { default as IconSun} from '@assets/icons/sun.svg?react';
export { default as IconMoon} from '@assets/icons/moon.svg?react';
export { default as IconVerified} from '@assets/icons/verified.svg?react';
export { default as IconSetting} from '@assets/icons/setting.svg?react';
export { default as IconLogout} from '@assets/icons/logout.svg?react';
export { default as IconReceipt} from '@assets/icons/receipt.svg?react';
export { default as IconDownload} from '@assets/icons/download.svg?react';
export { default as IconUsers} from '@assets/icons/users.svg?react';
export { default as IconMoreVertical} from '@assets/icons/more-vertical.svg?react';
export { default as IconLove} from '@assets/icons/love.svg?react';
export { default as IconCart} from '@assets/icons/cart.svg?react';
